Спринт 13. Попытка пройти тесты гита №1
Dw4yn33/java-shareit pull request #1
Opened 2023-08-31 21:58 UTC by Dw4yn33

2023-09-01 18:18 UTC, z8q requested changes

2023-09-01 18:18 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +    public static UserDto toUserDto(User user) {
В обратную сторону тоже можно сделать, чтобы в контроллере принимать dto.
А User использовать перед сохранением и перед тем, как достаем объект из мапы

2023-09-01 18:18 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @NotBlank
NotBlank проверяет на null тоже

2023-09-01 18:18 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto create(@RequestHeader(value = "X-Sharer-User-Id") Long id, @Valid @RequestBody Item item) {
Valid применяется к Item, но внутри Item нет валидационных аннотаций, соответственно валидация не осуществляется на уровне контроллера. Только уже на уровне репозитория

2023-09-01 18:18 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +        if (user.getName() == null || user.getName().isEmpty() || user.getName().isBlank() || user.getEmail() == null) {
isBlank проверяет на empty тоже

2023-09-01 18:18 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +        if (item.getName() == null || item.getName().isEmpty() || item.getDescription().isBlank()) {
третьим пунктом похоже предполагалась проверка name на isBlank.

2023-09-01 18:18 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserDto.java
> +    @Email
К аннотациям можно еще добавлять различные параметры, например сообщение об ошибке:
`@Email(message = "Not valid email")`

2023-09-02 13:43 UTC, Dw4yn33 commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +        if (user.getName() == null || user.getName().isEmpty() || user.getName().isBlank() || user.getEmail() == null) {
Исправлено

2023-09-02 13:43 UTC, Dw4yn33 commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +        if (item.getName() == null || item.getName().isEmpty() || item.getDescription().isBlank()) {
Исправлено

2023-09-02 13:44 UTC, Dw4yn33 commented on src/main/java/ru/practicum/shareit/user/UserDto.java
> +    @Email
Добавлено

2023-09-02 13:45 UTC, Dw4yn33 commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @NotBlank
Убрал notNull у ItemDto и UserDto

2023-09-02 14:00 UTC, Dw4yn33 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto create(@RequestHeader(value = "X-Sharer-User-Id") Long id, @Valid @RequestBody Item item) {
Перенес valid из всех запросов контроллеров в репозитории

2023-09-02 14:26 UTC, Dw4yn33 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto create(@RequestHeader(value = "X-Sharer-User-Id") Long id, @Valid @RequestBody Item item) {
С пользователем я поторопился, у него valid срабатывает только на уровне контроллера

2023-09-02 14:42 UTC, Dw4yn33 commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +    public static UserDto toUserDto(User user) {
Я сделал так, чтобы в контроллере принимались Dto, но аннотации в Dto на notNull и notBlank пришлось закомментировать. C ними тесты не проходят, так как в тестах есть запросы с предметом или пользователем, где сменить надо только почту или например только описание(в таких случаях остальные поля null).

2023-09-03 10:04 UTC, z8q approved these changes

2023-09-03 10:04 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto create(@RequestHeader(value = "X-Sharer-User-Id") Long id, @RequestBody ItemDto item) {
Было бы правильно оставить Valid на контроллере. Поставить валидационные аннотации над полями дто.
На контроллере отбивать невалидные запросы это хорошо. Лишний раз не запускать процессы выполнения логики.

2023-09-03 22:45 UTC, merged