Add bookings
Dw4yn33/java-shareit pull request #3
Opened 2023-09-19 10:16 UTC by Dw4yn33

2023-09-20 02:16 UTC, z8q requested changes

2023-09-20 02:16 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +    public UserDto create(UserDto userDto) {
Допускается сохранение пользователей с одинаковой почтой

2023-09-20 02:16 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +    public UserDto update(Long userId, UserDto userDto) {
Есть возможность сделать patch с пустыми полями
PATCH http://localhost:8080/users/9
```JSON
{
	"name": "",
	"email": ""
}
```

2023-09-20 02:16 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +    public ItemDto update(Long userId, Long itemId, ItemDto itemDto) {
при обновлении с пустым полем name приходит ошибка.
PATCH http://localhost:8080/items/1
```JSON
{
	"name": "",
	"description": "some description",
	"available": true
}
```
ответ
```JSON
{
	"error": "Error: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Error while committing the transaction"
}
```
Но можно было бы провалидировать поле через аннотацию над полем в дто, и вернуть описание ошибки

2023-09-20 02:16 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                                  @RequestParam(required = false, defaultValue = "ALL") String state) {
required = false можно убрать

2023-09-21 12:27 UTC, Dw4yn33 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                                  @RequestParam(required = false, defaultValue = "ALL") String state) {
Сделано

2023-09-21 12:29 UTC, Dw4yn33 commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +    public UserDto update(Long userId, UserDto userDto) {
Исправлено, приходит все равно код 200, но изменения больше не выполняются

2023-09-21 13:01 UTC, Dw4yn33 commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +    public UserDto create(UserDto userDto) {
Тесты postman проходят только так, я не могу это исправить, хоть и знаю как. Но для patch я сделал проверку на дубликаты почты.

2023-09-21 13:05 UTC, Dw4yn33 commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +    public ItemDto update(Long userId, Long itemId, ItemDto itemDto) {
Сделал так, чтобы поле больше не обновлялось, если является пустым

2023-09-22 12:33 UTC, z8q approved these changes

2023-09-30 22:15 UTC, merged