Спринт 15. Попытка №1.
Dw4yn33/java-shareit pull request #4
Opened 2023-10-01 16:40 UTC by Dw4yn33

2023-10-01 22:03 UTC, z8q requested changes

2023-10-01 22:03 UTC, z8q commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +    UserRepository userRepository;
Тут используем `@SpringBootTest` и `@AutoConfigureTestDatabase`, то есть при запуске теста у нас еще есть база.
Но репозитории почему-то мокаются.
Предположим, что убрали строки с 56 по 66.
Чтобы выполнить тест testCreateComment, нам надо убрать все Mockito.when, Mockito.verify.
И прямо создавать пользователя, создавать вещь, создавать бронирование:
userService.create(userDto);
itemService.create(userDto.getId(), itemDto);
bookingService.createBooking(...)

репозитории будут работать

и уже потом создавать:
CommentDto commentDto = itemService.createComment(1L, 1L, commentRequestDto);

Тогда тест будет интереснее)

2023-10-01 22:03 UTC, z8q commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +package ru.practicum.shareit.booking;
Не хватает тестов для слоя репозиториев с применением аннотации `@DataJpaTest`

2023-10-02 18:54 UTC, Dw4yn33 commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +    UserRepository userRepository;
Сделано, только equals для commentDto пришлось немного не по-честному сделать, чтобы тесты показывали точное(почти) равенство объектов, ибо по какой-то причине у комментария, сохраненного в объекте предмета время на 600 наносекунд больше, чем просто у commentDto, который собственно и добавляли в предмет по тестам

2023-10-04 16:49 UTC, Dw4yn33 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +package ru.practicum.shareit.booking;
Сделал. Если тесты jpa написаны правильно, то пожалуйста, примите этот спринт, мне нужно еще успеть сдать 16 спринт, а времени совсем мало осталось.

2023-10-04 19:18 UTC, z8q approved these changes

2023-10-06 13:06 UTC, merged