Спринт 16.
Dw4yn33/java-shareit pull request #6
Opened 2023-10-09 10:49 UTC by Dw4yn33

2023-10-09 19:01 UTC, z8q requested changes

2023-10-09 19:01 UTC, z8q commented on server/src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @NotBlank
По заданию из тз нужно будет убрать валидацию из server.  Вся валидация полей должна происходить в gateway

2023-10-09 19:01 UTC, z8q commented on server/pom.xml
> +			<artifactId>jakarta.validation-api</artifactId>
Зависимости, которые связаны с валидацией, нужно будет тоже убрать

2023-10-09 19:20 UTC, Dw4yn33 commented on server/pom.xml
> +			<artifactId>jakarta.validation-api</artifactId>
Сделано

2023-10-09 19:20 UTC, Dw4yn33 commented on server/src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @NotBlank
Сделано

2023-10-10 15:50 UTC, z8q approved these changes

2023-10-10 15:54 UTC, merged